@php($primaryAddress = $primaryAddress ?? null)
@php($hasTaxError = $errors->hasAny(['tax_number', 'branch_type', 'branch_number']))
<div class="card"><div class="card-header"><h3 class="card-title">ข้อมูลลูกค้า</h3></div><div class="card-body">
    @if ($isEdit)<div class="form-group"><label for="customer-code">รหัสลูกค้า</label><input id="customer-code" class="form-control" value="{{ $customer->code }}" readonly></div>@endif
    <div class="form-group"><label for="customer-name">ชื่อลูกค้า <span class="text-danger">*</span></label><input id="customer-name" name="name" value="{{ old('name', $customer->name ?? '') }}" class="form-control @error('name') is-invalid @enderror" required autofocus>@error('name')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
    <div class="form-group"><label for="customer-phone">เบอร์ลูกค้า</label><input id="customer-phone" name="phone" value="{{ old('phone', $customer->phone ?? '') }}" class="form-control @error('phone') is-invalid @enderror">@error('phone')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
</div></div>

<div class="card"><div class="card-header"><h3 class="card-title">ที่อยู่จัดส่งหลัก</h3></div><div class="card-body">
    @if ($isEdit)<input type="hidden" name="primary_address_id" value="{{ $primaryAddress?->id }}">@endif
    <div class="form-group"><label for="delivery-zone">พื้นที่จัดส่ง</label><select id="delivery-zone" name="delivery_zone_id" class="form-control @error('delivery_zone_id') is-invalid @enderror"><option value="">เลือกพื้นที่จัดส่ง</option>@foreach ($deliveryZones as $zone)<option value="{{ $zone->id }}" @selected(old('delivery_zone_id', $primaryAddress?->delivery_zone_id ?? '') == $zone->id)>{{ $zone->name }}</option>@endforeach</select>@error('delivery_zone_id')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
    <div class="form-group"><label for="delivery-address">รายละเอียดที่อยู่</label><textarea id="delivery-address" name="address" rows="3" class="form-control @error('address') is-invalid @enderror" placeholder="เช่น 99/1 ม.2 ข้างวัด หรือไซต์งานหลังโรงสี">{{ old('address', $primaryAddress?->address ?? '') }}</textarea>@error('address')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
    <div class="form-check mb-3"><input id="use-customer-phone" name="use_customer_phone" value="1" type="checkbox" class="form-check-input" @checked(old('use_customer_phone', !$isEdit || $primaryAddress?->receiver_phone === ($customer->phone ?? null)))><label for="use-customer-phone" class="form-check-label">ใช้เบอร์ลูกค้าเป็นเบอร์ผู้รับของ</label></div>
    <div class="form-group"><label for="receiver-phone">เบอร์ผู้รับของ</label><input id="receiver-phone" name="receiver_phone" value="{{ old('receiver_phone', $primaryAddress?->receiver_phone ?? '') }}" class="form-control @error('receiver_phone') is-invalid @enderror">@error('receiver_phone')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
</div></div>

<div class="card"><div class="card-header"><h3 class="card-title">หมายเหตุ</h3></div><div class="card-body"><textarea name="remark" rows="3" class="form-control @error('remark') is-invalid @enderror" placeholder="โทรก่อนส่ง / รับของช่วงบ่าย">{{ old('remark', $customer->remark ?? '') }}</textarea>@error('remark')<div class="invalid-feedback">{{ $message }}</div>@enderror</div></div>

<div class="card"><div class="card-header"><a data-toggle="collapse" href="#tax-fields" aria-expanded="{{ $isEdit || $hasTaxError ? 'true' : 'false' }}">ข้อมูลใบกำกับภาษี</a></div><div id="tax-fields" class="collapse {{ $isEdit || $hasTaxError ? 'show' : '' }}"><div class="card-body">
    <div class="form-group"><label>ชื่อ/ข้อมูลลูกค้าใบกำกับภาษี</label><input name="tax_number" value="{{ old('tax_number', $customer->tax_number ?? '') }}" class="form-control @error('tax_number') is-invalid @enderror">@error('tax_number')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
    <div class="row"><div class="col-md-6 form-group"><label>ประเภทสาขา</label><select name="branch_type" class="form-control"><option value="สำนักงานใหญ่" @selected(old('branch_type', $customer->branch_type ?? 'สำนักงานใหญ่') === 'สำนักงานใหญ่')>สำนักงานใหญ่</option><option value="สาขา" @selected(old('branch_type', $customer->branch_type ?? '') === 'สาขา')>สาขา</option></select></div><div class="col-md-6 form-group"><label>เลขสาขา</label><input name="branch_number" value="{{ old('branch_number', $customer->branch_number ?? '') }}" class="form-control @error('branch_number') is-invalid @enderror">@error('branch_number')<div class="invalid-feedback">{{ $message }}</div>@enderror</div></div>
</div></div></div>

<div class="d-flex justify-content-end mb-4"><a href="{{ $isEdit ? route('customers.show', $customer) : route('customers.index') }}" class="btn btn-secondary mr-2">ยกเลิก</a><button class="btn btn-success" type="submit">{{ $isEdit ? 'บันทึกการแก้ไข' : 'บันทึกลูกค้า' }}</button></div>
